// Pure codegen logic: validate the fields the classifiers read and build
// compact tables. Full JSON Schema validation stays in pre-commit and the
// Python suite. Erasable TypeScript only: this runs under Node's type stripping.
import { normalizeHost } from "../src/host.ts";
import type { CrawlerRow, Purpose, ReferrerRow, TokenRow } from "../src/types.ts";

const PURPOSES: readonly string[] = ["training", "user_fetch", "search_index"];

export interface Tables {
  referrers: ReferrerRow[];
  crawlers: CrawlerRow[];
  /** Every crawler in signals.json order, robots_only included. */
  all: TokenRow[];
}

function fail(message: string): never {
  throw new Error(`signals.json: ${message}`);
}

function record(value: unknown, where: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    fail(`${where} must be an object`);
  }
  return value as Record<string, unknown>;
}

function text(obj: Record<string, unknown>, key: string, where: string): string {
  const value = obj[key];
  if (typeof value !== "string" || value === "") fail(`${where}.${key} must be a non-empty string`);
  return value;
}

function list(obj: Record<string, unknown>, key: string, where: string): unknown[] {
  const value = obj[key];
  if (!Array.isArray(value)) fail(`${where}.${key} must be an array`);
  return value;
}

export function buildTables(signals: unknown): Tables {
  const root = record(signals, "root");
  if (root.schema_version !== 1) fail(`unsupported schema_version ${String(root.schema_version)}`);
  const ids = new Set<string>();
  const claim = (id: string, where: string): void => {
    if (ids.has(id)) fail(`${where}: duplicate id ${id}`);
    ids.add(id);
  };

  const crawlers: CrawlerRow[] = [];
  const all: TokenRow[] = [];
  list(root, "crawlers", "root").forEach((raw, i) => {
    const where = `crawlers[${i}]`;
    const c = record(raw, where);
    const id = text(c, "id", where);
    claim(id, where);
    const match = text(c, "match", where);
    if (match !== "user_agent" && match !== "robots_only") {
      fail(`${where}.match must be user_agent or robots_only`);
    }
    const purpose = text(c, "purpose", where);
    if (!PURPOSES.includes(purpose)) fail(`${where}.purpose ${purpose} is not a known purpose`);
    const aiSpecific = c.ai_specific;
    if (typeof aiSpecific !== "boolean") fail(`${where}.ai_specific must be a boolean`);
    const token = text(c, "token", where);
    all.push([
      id,
      text(c, "vendor", where),
      text(c, "vendor_name", where),
      token,
      purpose as Purpose,
      aiSpecific,
      match === "robots_only",
    ]);
    if (match === "user_agent") {
      crawlers.push([
        id,
        text(c, "vendor", where),
        text(c, "vendor_name", where),
        token,
        purpose as Purpose,
        aiSpecific,
      ]);
    }
  });
  // Longest token first, so a longer token wins over a shorter one it contains.
  // Array.prototype.sort is stable, so equal lengths keep signals.json order,
  // exactly like Python's list.sort(key=..., reverse=True).
  crawlers.sort((a, b) => b[3].length - a[3].length);

  const hosts = new Set<string>();
  const referrers = list(root, "referrers", "root").map((raw, i): ReferrerRow => {
    const where = `referrers[${i}]`;
    const r = record(raw, where);
    const id = text(r, "id", where);
    claim(id, where);
    const normalized = list(r, "hosts", where).map((h, j) => {
      if (typeof h !== "string" || h === "")
        fail(`${where}.hosts[${j}] must be a non-empty string`);
      const host = normalizeHost(h);
      if (hosts.has(host)) fail(`${where}: host ${host} is listed twice`);
      hosts.add(host);
      return host;
    });
    if (normalized.length === 0) fail(`${where}.hosts must not be empty`);
    return [
      id,
      text(r, "vendor", where),
      text(r, "vendor_name", where),
      text(r, "product", where),
      normalized,
    ];
  });
  return { referrers, crawlers, all };
}

export function renderModule(
  constName: string,
  typeName: "ReferrerRow" | "CrawlerRow" | "TokenRow",
  rows: readonly unknown[],
): string {
  const body = rows.map((row) => `  ${JSON.stringify(row)},`).join("\n");
  return [
    "// Generated by scripts/codegen.ts from signals.json. Do not edit.",
    `import type { ${typeName} } from "./types.js";`,
    "",
    `export const ${constName}: readonly ${typeName}[] = [`,
    body,
    "];",
    "",
  ].join("\n");
}
