import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { buildTables, renderModule } from "../scripts/tables.ts";
import { normalizeHost } from "../src/host.js";

const crawler = (id: string, token: string, extra: Record<string, unknown> = {}) => ({
  id,
  vendor: "v",
  vendor_name: "V",
  token,
  match: "user_agent",
  purpose: "training",
  ai_specific: true,
  ...extra,
});
const referrer = (id: string, hosts: unknown[]) => ({
  id,
  vendor: "v",
  vendor_name: "V",
  product: id.toUpperCase(),
  hosts,
});
const signals = (over: Record<string, unknown> = {}) => ({
  schema_version: 1,
  crawlers: [],
  referrers: [],
  ...over,
});

describe("normalizeHost", () => {
  it.each([
    ["WWW.Example.COM", "example.com"],
    ["claude.ai.", "claude.ai"],
    ["claude.ai..", "claude.ai"],
    [" www.www.x.com ", "www.x.com"],
    ["wwwx.com", "wwwx.com"],
  ])("%s -> %s", (input, expected) => {
    expect(normalizeHost(input)).toBe(expected);
  });
});

describe("normalizeHost on hostile input", () => {
  // A regex like /\.+$/ backtracks quadratically on a long run of dots that
  // isn't at the end; the ESM classifier can receive raw Referer headers.
  it("stays linear on a long run of dots", () => {
    const hostile = `${".".repeat(50_000)}x`;
    const started = performance.now();
    expect(normalizeHost(hostile)).toBe(hostile);
    expect(performance.now() - started).toBeLessThan(50);
  });
});

describe("buildTables", () => {
  it("keeps only user_agent crawlers, longest token first, ties in file order", () => {
    const { crawlers } = buildTables(
      signals({
        crawlers: [
          crawler("a", "Bot"),
          crawler("b", "LongerBot"),
          crawler("c", "Ext-Token", { match: "robots_only" }),
          crawler("d", "Cat"),
        ],
      }),
    );
    expect(crawlers.map((row) => row[3])).toEqual(["LongerBot", "Bot", "Cat"]);
    expect(crawlers[0]).toEqual(["b", "v", "V", "LongerBot", "training", true]);
  });

  it("normalises referrer hosts", () => {
    const { referrers } = buildTables(
      signals({ referrers: [referrer("x", ["WWW.Chat.Example.", "chat2.example"])] }),
    );
    expect(referrers).toEqual([["x", "v", "V", "X", ["chat.example", "chat2.example"]]]);
  });

  it.each([
    ["unsupported schema_version", signals({ schema_version: 2 })],
    ["duplicate id", signals({ crawlers: [crawler("a", "A"), crawler("a", "B")] })],
    ["purpose", signals({ crawlers: [crawler("a", "A", { purpose: "spying" })] })],
    ["match", signals({ crawlers: [crawler("a", "A", { match: "header" })] })],
    ["token", signals({ crawlers: [crawler("a", "A", { token: 7 })] })],
    ["ai_specific", signals({ crawlers: [crawler("a", "A", { ai_specific: "yes" })] })],
    [
      "listed twice",
      signals({ referrers: [referrer("x", ["a.com"]), referrer("y", ["WWW.A.com"])] }),
    ],
    ["must not be empty", signals({ referrers: [referrer("x", [])] })],
    ["hosts[0]", signals({ referrers: [referrer("x", [""])] })],
  ])("rejects %s", (message, bad) => {
    expect(() => buildTables(bad)).toThrow(message);
  });

  it("covers every entry in the real signals.json", () => {
    const real = JSON.parse(
      readFileSync(new URL("../../../signals.json", import.meta.url), "utf8"),
    ) as { crawlers: { id: string; match: string }[]; referrers: { id: string }[] };
    const { crawlers, referrers } = buildTables(real);
    const uaIds = real.crawlers.filter((c) => c.match === "user_agent").map((c) => c.id);
    expect(crawlers.map((row) => row[0]).sort()).toEqual([...uaIds].sort());
    expect(referrers.map((row) => row[0])).toEqual(real.referrers.map((r) => r.id));
    expect(buildTables(real).all.map((row) => row[0])).toEqual(real.crawlers.map((c) => c.id));
  });

  it("all keeps every crawler in file order, flagging robots_only", () => {
    const { all } = buildTables(
      signals({
        crawlers: [crawler("a", "Bot"), crawler("c", "Ext-Token", { match: "robots_only" })],
      }),
    );
    expect(all).toEqual([
      ["a", "v", "V", "Bot", "training", true, false],
      ["c", "v", "V", "Ext-Token", "training", true, true],
    ]);
  });
});

describe("renderModule", () => {
  it("renders a typed, generated TS module", () => {
    expect(renderModule("REFERRERS", "ReferrerRow", [["x", "v", "V", "X", ["x.com"]]])).toBe(
      [
        "// Generated by scripts/codegen.ts from signals.json. Do not edit.",
        'import type { ReferrerRow } from "./types.js";',
        "",
        "export const REFERRERS: readonly ReferrerRow[] = [",
        '  ["x","v","V","X",["x.com"]],',
        "];",
        "",
      ].join("\n"),
    );
  });
});
